export const buyHypo = 'buyHypo'
export const sellHypo = 'sellHypo'
export const buyReal = 'buyReal'
export const sellReal = 'sellReal'
export const dividendReal = 'dividendReal'
export const dividendHypo = 'dividendHypo'
export const realWorth = 'realWorth'
export const hypoWorth = 'hypoWorth'
